import {test,expect} from '@playwright/test'
import {quests} from '../shared/content.js'
test.use({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block',launchOptions:{chromiumSandbox:true}})
const base=process.env.SHANHE_TEST_URL||'http://127.0.0.1:8812'
test.beforeEach(async({context})=>{await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin===new URL(base).origin||u.protocol==='data:'||u.protocol==='blob:')await route.continue();else await route.abort()})})
test('手机任务回答后逐项展开、返回、刷新存档与标签滚动恢复',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(base);await expect(page.getByText('正在读取本机存档',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('heading',{name:'把日常留在身后。'})).toBeVisible()
 await page.getByRole('button',{name:'开启我的探索'}).click()
 const dialog=page.getByRole('dialog'),quest=quests[0];await expect(dialog).toBeVisible()
 await expect(dialog.getByRole('textbox')).toHaveCount(1)
 await expect(dialog.getByText(quest.actions[1].text,{exact:true})).toHaveCount(0)
 await expect(dialog.getByRole('button',{name:'提交记录，展开下一项'})).toBeDisabled()
 await dialog.getByRole('textbox').fill('入口展板上看到了参观动线，我选择沿开放展区前行。')
 await dialog.getByRole('button',{name:'提交记录，展开下一项'}).click()
 await expect(dialog.locator('.answer-record')).toHaveCount(1)
 await expect(dialog.getByText(quest.actions[1].text,{exact:true})).toBeVisible()
 await dialog.getByRole('button',{name:'返回上一层'}).click();await expect(dialog).toHaveCount(0)
 await page.reload();await page.getByRole('button',{name:'开启我的探索'}).click()
 await expect(dialog.locator('.answer-record')).toHaveCount(1)
 await expect(dialog.getByRole('textbox')).toHaveValue('')
 for(let i=1;i<quest.actions.length;i++){
   await dialog.getByRole('textbox').fill(`第${i+1}步，我记下器物边缘的细节和展牌出处。`)
   await dialog.getByRole('button',{name:/提交记录，/}).click()
   await expect(dialog.locator('.answer-record')).toHaveCount(i+1)
 }
 await expect(dialog.getByText('一条线索，收入手记。')).toBeVisible()
 await expect(dialog.getByRole('textbox')).toHaveCount(0)
 await page.goBack();await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('navigation',{name:'移动端导航'}).getByRole('button',{name:'路线',exact:true}).click()
 await page.evaluate(()=>window.scrollTo(0,1000));await page.waitForTimeout(150);const top=await page.evaluate(()=>scrollY)
 await page.getByRole('navigation',{name:'移动端导航'}).getByRole('button',{name:'手记',exact:true}).click()
 await page.getByRole('navigation',{name:'移动端导航'}).getByRole('button',{name:'路线',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>scrollY)).toBeCloseTo(top,-1)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy()
 expect(errors).toEqual([])
})
test('手机新建旅程、检查点、输入不缩放和返回导航',async({page})=>{
 await page.goto(base+'/#mine');await expect(page.getByRole('button',{name:'新建旅程',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'新建旅程',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible()
 const input=dialog.getByRole('textbox');expect(await input.evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(16)
 await input.fill('手机测试旅程');await dialog.getByRole('button',{name:'确认',exact:true}).click();await expect(page.getByRole('button',{name:/手机测试旅程/})).toBeVisible()
 await page.getByRole('button',{name:'保存当前检查点'}).click();await page.getByRole('dialog').getByRole('textbox').fill('出发前');await page.getByRole('dialog').getByRole('button',{name:'确认',exact:true}).click();await expect(page.getByText('出发前',{exact:true})).toBeVisible()
 await page.screenshot({path:'test-results/mobile-account.png',fullPage:true})
})
