import React,{useEffect,useState} from 'react'
import {api} from './api'
import Modal from './Modal'
export default function AccountTools({user,ask,refresh}:{user:{id:string;role:string};ask:(title:string,value?:string,password?:boolean)=>Promise<string|null>;refresh:()=>Promise<void>}){
 const [invites,setInvites]=useState<any[]>([]),[message,setMessage]=useState(''),[passwordForm,setPasswordForm]=useState(false),[busy,setBusy]=useState(false)
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'操作未完成')}finally{setBusy(false)}}
 async function load(){setInvites((await api('/admin/invites')).invites)}
 useEffect(()=>{if(user.role==='admin')void run(load)},[user.id])
 return <section className="settings-panel admin-panel"><h2>账户安全</h2><p>修改口令会撤销已登录设备的会话，需要重新登录。</p><button className="button outline" onClick={()=>setPasswordForm(true)}>修改我的口令</button>{user.role==='admin'&&<><div className="section-heading"><h2>已发出的邀请</h2><button className="link-button" disabled={busy} onClick={()=>run(load)}>刷新邀请</button></div>{invites.length?invites.map(v=><div className="admin-row" key={v.id}><span>{v.role==='admin'?'管理员开通':'同行者邀请'}<small style={{display:'block'}}>到期：{new Date(v.expires).toLocaleString()} · {v.used?'已使用或撤销':'待使用'}</small></span><button className="link-button" disabled={busy||Boolean(v.used)} onClick={()=>run(async()=>{const password=await ask('验证口令后撤销邀请','',true);if(!password)return;await api(`/admin/invites/${v.id}/revoke`,{method:'POST',body:{password}});await load()})}>撤销</button></div>):<p>还没有发出邀请。</p>}</>}{message&&<p role="status">{message}</p>}{passwordForm&&<Modal title="修改我的口令" onClose={()=>setPasswordForm(false)}><form className="auth-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api('/auth/password',{method:'POST',body:{currentPassword:f.get('current'),newPassword:f.get('next')}});setPasswordForm(false);await refresh()})}}><label>当前口令<input name="current" type="password" autoComplete="current-password" required minLength={12} maxLength={128}/></label><label>新口令<input name="next" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label><button className="button primary" disabled={busy}>确认修改并退出旧会话</button><p role="status">{message}</p></form></Modal>}</section>
}
